## Association Rule Mining Using Apriori Algorithm

In [1]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (2.4.6)
Requirement already satisfied: pandas>=2.3.3 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (3.0.3)
Requirement already satisfied: scikit-learn>=1.8.0 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (3.11.0)
Requirement already satisfied: joblib>=1.5.2 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.2)
Requirement already satisfied: pillow>=9 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: six>=1.5 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in G:\Meu Drive\Cursos\Python\MachineLearning\.venv\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 340.2 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 340.2 kB/s eta 0:00:03
   --------------- ------------------------ 0.5/1.4 MB 340.2 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 413.2 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 476.9 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 476.9 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 530.7 kB/s  0:00:02
Installing collected packages: mlxtend
Successfully installed mlxtend-0.25.0

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [4]:
data = pd.read_csv('G:/Meu Drive/Cursos/Python/MachineLearning/Parte2/data/groceries.csv')
data.head()

                  1                    2               3  ...    7    8    9
0      citrus fruit  semi-finished bread       margarine  ...  NaN  NaN  NaN
1    tropical fruit               yogurt          coffee  ...  NaN  NaN  NaN
2        whole milk                  NaN             NaN  ...  NaN  NaN  NaN
3         pip fruit               yogurt   cream cheese   ...  NaN  NaN  NaN
4  other vegetables           whole milk  condensed milk  ...  NaN  NaN  NaN

[5 rows x 9 columns]

In [5]:
baskets_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [6]:
baskets_sets.head()

   Instant food products  UHT-milk  ...  yogurt  zwieback
0                      0         0  ...       0         0
1                      0         0  ...       1         0
2                      0         0  ...       0         0
3                      0         0  ...       1         0
4                      0         0  ...       0         0

[5 rows x 165 columns]

In [7]:
baskets_sets_bool = baskets_sets.astype(bool)
apriori(baskets_sets_bool,min_support=0.02)

      support                    itemsets
0    0.028155              frozenset({1})
1    0.054369              frozenset({8})
2    0.032039              frozenset({9})
3    0.027508             frozenset({10})
4    0.072492             frozenset({11})
..        ...                         ...
105  0.022977       frozenset({154, 163})
106  0.033981       frozenset({162, 158})
107  0.055987       frozenset({162, 163})
108  0.022977  frozenset({121, 162, 101})
109  0.022977  frozenset({162, 163, 101})

[110 rows x 2 columns]

In [8]:
baskets_sets_bool = baskets_sets.astype(bool)
apriori(baskets_sets_bool,min_support=0.02, use_colnames=True)

      support                                           itemsets
0    0.028155                              frozenset({UHT-milk})
1    0.054369                                  frozenset({beef})
2    0.032039                               frozenset({berries})
3    0.027508                             frozenset({beverages})
4    0.072492                          frozenset({bottled beer})
..        ...                                                ...
105  0.022977                frozenset({tropical fruit, yogurt})
106  0.033981        frozenset({whipped/sour cream, whole milk})
107  0.055987                    frozenset({yogurt, whole milk})
108  0.022977  frozenset({root vegetables, other vegetables, ...
109  0.022977  frozenset({yogurt, other vegetables, whole milk})

[110 rows x 2 columns]

In [10]:
df_combo = baskets_sets.astype(bool)

frequent_itemsets = apriori(df_combo, min_support=0.002, use_colnames=True)

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

frequent_itemsets

       support                                           itemsets  length
0     0.007120                 frozenset({Instant food products})       1
1     0.028155                              frozenset({UHT-milk})       1
2     0.002913                      frozenset({abrasive cleaner})       1
3     0.003560                      frozenset({artif. sweetener})       1
4     0.014887                         frozenset({baking powder})       1
...        ...                                                ...     ...
2313  0.002265  frozenset({root vegetables, yogurt, other vege...       5
2314  0.002589  frozenset({yogurt, other vegetables, whipped/s...       5
2315  0.002265  frozenset({pip fruit, yogurt, other vegetables...       5
2316  0.002265  frozenset({root vegetables, tropical fruit, yo...       5
2317  0.002265  frozenset({yogurt, tropical fruit, other veget...       5

[2318 rows x 3 columns]

In [11]:
frequent_itemsets[(frequent_itemsets['length']>=3)]

       support                                           itemsets  length
1260  0.002589  frozenset({UHT-milk, bottled water, other vege...       3
1261  0.002265         frozenset({UHT-milk, soda, bottled water})       3
1262  0.002589  frozenset({baking powder, other vegetables, wh...       3
1263  0.002265  frozenset({whipped/sour cream, baking powder, ...       3
1264  0.002589             frozenset({berries, whole milk, beef})       3
...        ...                                                ...     ...
2313  0.002265  frozenset({root vegetables, yogurt, other vege...       5
2314  0.002589  frozenset({yogurt, other vegetables, whipped/s...       5
2315  0.002265  frozenset({pip fruit, yogurt, other vegetables...       5
2316  0.002265  frozenset({root vegetables, tropical fruit, yo...       5
2317  0.002265  frozenset({yogurt, tropical fruit, other veget...       5

[1058 rows x 3 columns]

In [13]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.9)
rules.head()

                                   antecedents  ... kulczynski
0            frozenset({hamburger meat, curd})  ...   0.506305
1    frozenset({root vegetables, frozen fish})  ...   0.504414
2  frozenset({sausage, yogurt, bottled water})  ...   0.464708
3    frozenset({sausage, soda, bottled water})  ...   0.466366
4   frozenset({butter, pip fruit, whole milk})  ...   0.462949

[5 rows x 14 columns]

In [15]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

                          antecedents  ... kulczynski
0       frozenset({other vegetables})  ...   0.164973
1  frozenset({Instant food products})  ...   0.164973
2        frozenset({root vegetables})  ...   0.169385
3  frozenset({Instant food products})  ...   0.169385
4               frozenset({UHT-milk})  ...   0.143844

[5 rows x 14 columns]

In [19]:
rules[(rules['lift']>=5) & (rules['confidence']>=0.8)]

                                            antecedents  ... kulczynski
7111        frozenset({sausage, yogurt, bottled water})  ...   0.464708
7112          frozenset({sausage, soda, bottled water})  ...   0.466366
7378      frozenset({canned beer, rolls/buns, sausage})  ...   0.451172
8132  frozenset({whipped/sour cream, dessert, other ...  ...   0.453901
8187  frozenset({pastry, frankfurter, other vegetabl...  ...   0.505824
8313      frozenset({hamburger meat, pork, whole milk})  ...   0.506723

[6 rows x 14 columns]