# Removendo dados Duplicado

In [ ]:
# Importando as bibliotecas
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [ ]:
DF_obj = DataFrame({'column 1':[1,1,2,2,3,3,3],
                    'column 2':['a','a','b','b','c','c','c'],
                    'column 3':['A','A','B','B','C','C','C']})
DF_obj

In [ ]:
# Mostra se a linha está duplicada, ou seja, false e é a primeira ocorrência e true se é uma ocorrência duplicada
DF_obj.duplicated()

In [ ]:
# Remove as linhas duplicadas
DF_obj.drop_duplicates()

## Criando outro Dataframe

In [9]:
DF_obj = DataFrame({'column 1':[1,1,2,2,3,3,3],
                    'column 2':['a','a','b','b','c','c','c'],
                    'column 3':['A','A','B','B','C','D','C']})
DF_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        D
6         3        c        C

In [ ]:
# Removendo dados duplicados apenas de uma coluna
DF_obj.drop_duplicates(['column 3'])

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        D