# Removendo dados Duplicado

In [1]:
!pip install --upgrade pip
!pip install pandas

Requirement already satisfied: pip in .\.venv\lib\site-packages (26.1.2)
Requirement already satisfied: pandas in .\.venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in .\.venv\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in .\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in .\.venv\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# Importando as bibliotecas
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
DF_obj = DataFrame({'column 1':[1,1,2,2,3,3,3],
                    'column 2':['a','a','b','b','c','c','c'],
                    'column 3':['A','A','B','B','C','C','C']})
DF_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        C
6         3        c        C

In [4]:
# Mostra se a linha está duplicada, ou seja, false e é a primeira ocorrência e true se é uma ocorrência duplicada
DF_obj.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [5]:
# Remove as linhas duplicadas
DF_obj.drop_duplicates()

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C

## Criando outro Dataframe

In [6]:
DF_obj = DataFrame({'column 1':[1,1,2,2,3,3,3],
                    'column 2':['a','a','b','b','c','c','c'],
                    'column 3':['A','A','B','B','C','D','C']})
DF_obj

   column 1 column 2 column 3
0         1        a        A
1         1        a        A
2         2        b        B
3         2        b        B
4         3        c        C
5         3        c        D
6         3        c        C

In [7]:
# Removendo dados duplicados apenas de uma coluna
DF_obj.drop_duplicates(['column 3'])

   column 1 column 2 column 3
0         1        a        A
2         2        b        B
4         3        c        C
5         3        c        D